name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable-x86_64-unknown-linux-gnu --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Clippy
        run: cargo clippy --all-features --all-targets
  uds-cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup toolchain install stable-x86_64-unknown-linux-gnu --profile minimal
      - uses: Swatinem/rust-cache@v2
      - name: Test run
        run: cargo run -p uds-cron

